 CREATE DATABASE IF NOT EXISTS cine;
 USE cine;
 CREATE TABLE usuarios (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(100) NOT NULL,
 correo VARCHAR(100) NOT NULL UNIQUE,
 contraseña VARCHAR(255) NOT NULL
 );